FROM node:20-alpine AS deps
WORKDIR /app/bot
COPY bot/package*.json ./
RUN npm install

FROM node:20-alpine
WORKDIR /app/bot
ENV NODE_ENV=production
COPY --from=deps /app/bot/node_modules ./node_modules
COPY bot .
RUN npm run build
CMD ["npm", "run", "start"]
